spring.datasource.url=jdbc:h2:mem:clinicadb
spring.datasource.username=root
spring.datasource.password=
spring.h2.console.enabled=true
<<<<<<< HEAD

=======
>>>>>>> 7f0c1f573623ede75d0b60d8c8988d335becd68d
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldU
